### PR TITLE
Added eco device auto discovery and device status polling

### PR DESCRIPTION
**Pull request by NorthernMan54**
Hi,

This is a first draft of an attempt of implementing device auto discovery and device status polling, as I really dislike editing config files. I also split the eco specific code into a separate library to make it easier to maintain and follow the homebridge flows.

For device auto discovery, it sends out a device discovery packet every 60 seconds, and adds any new devices discovered as a result.

For device status polling, it sends a device status request out to all the known devices every 10 seconds, and updates homebridge with the device status.

### CODE REVIEW

**Comment by Danimal4326** [comment]
Hi,

I haven't had time to test this yet.  When I get some time this weekend I'll take a look and hopefully merge it in.

**Comment by Danimal4326** [comment]
I've merged your branch into a new branch on here to test (auto-discovery)
Currently, I cant get it to run, as it errors out on start:

/usr/local/lib/node_modules/homebridge-ecoplug/index.js:155
        .getCharacteristic(Characteristic.On)
        ^

TypeError: Cannot read property 'getCharacteristic' of undefined
    at EcoPlugPlatform.setService (/usr/local/lib/node_modules/homebridge-ecoplug/index.js:155:9)
    at EcoPlugPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-ecoplug/index.js:34:10)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:342:24)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:83:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by Danimal4326** [comment]
looks like it was some sort of homebridge cache issue..  working now

**Comment by Danimal4326** [comment]
Bumped version to 0.3.0 and published this to NPM.  Thanks for the updates!!!

**Comment by NorthernMan54** [comment]
Tks

**Pull request merged**
